# These are supported funding model platforms

github: [dj-arnold] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
buy_me_a_coffee: djarnold # Replace with a single Buy Me a Coffee username
thanks_dev: dj-arnold # Replace with a single thanks.dev username
